# A1: Exercise

최규빈  
2025-01-01

<a href="https://colab.research.google.com/github/guebin/DL2025/blob/main/posts/exercise.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" style="text-align: left"></a>

> 문제풀이에 필요한 모듈은 스스로 `import` 할 것

## `$`. 벡터와 행렬

`#`. 아래와 같이 length 5 인 vector를 `torch.tensor`로 선언하는 코드를
작성하라.

$${\bf x} = [1,2,3,4,5]$$

`(풀이)`

In [2]:
x = torch.tensor([1,2,3,4,5])
x

`#`. 아래와 같은 2x2 matrix 를 `torch.tensor`로 선언하는 코드를
작성하라.

$${\bf A} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$$

`#`. 아래와 같은 matrix 를 `torch.tensor`로 선언하는 코드를 작성하라.

$${\bf W} = \begin{bmatrix} 2.5  \\  4 \end{bmatrix}$$

`#`. 아래와 같은 matrix 를 `torch.tensor`로 선언하는 코드를 작성하라.

$${\bf x} = \begin{bmatrix} 2.5  & 4 \end{bmatrix}$$

## `$`. concat, stack

a,b가 아래와 같이 주어졌다고 하자.

In [9]:
a = torch.tensor([1]*10)
b = torch.tensor([2]*10)

아래를 잘 읽고 물음에 답하라.

`#`. 주어진 a,b와 `torch.concat`를 이용하여 아래와 같은 배열을 만들어라.

    tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
torch.concat([a.reshape(-1,1), b.reshape(-1,1)])

`#`. 주어진 a,b 와 `torch.concat`,`.reshape`를 이용하여 아래와 같은
배열을 만들어라.

    tensor([[1],
            [1],
            [1],
            [1],
            [1],
            [1],
            [1],
            [1],
            [1],
            [1],
            [2],
            [2],
            [2],
            [2],
            [2],
            [2],
            [2],
            [2],
            [2],
            [2]])

`#`. 주어진 a,b 와 `torch.concat`,`.reshape`를 이용하여 아래와 같은
배열을 만들어라.

    tensor([[1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2]])

`#`. 주어진 a,b와 `torch.stack` 을 이용하여 아래와 같은 배열을 만들어라.

    tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]

`#`. 주어진 a,b와 `torch.stack`을 이용하여 아래와 같은 배열을 만들어라.

    tensor([[1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2]])

## `$`. 행렬곱

`#`. 아래와 같은 텐서를 고려하자.

In [3]:
a = torch.tensor([1,2,3,4,5]).reshape(-1,1)
b = torch.tensor([3,2,1,1,2]).reshape(-1,1)

`@` 연산자를 이용하여 $\sum_{i=1}^{5}a_ib_i$를 계산하라.

`(풀이)`

In [4]:
a.T @ b

`#`. 아래와 같은 텐서를 고려하자.

In [6]:
torch.manual_seed(0)
x = torch.randn(100).reshape(-1,1)

`@`연산자를 이용하여 $\sum_{i=1}^{100}x_i^2$을 계산하라.

## `$`. 인덱싱

아래와 같은 배열을 선언하라.

In [23]:
torch.manual_seed(1)
x = torch.randn(12).reshape(3,4)
x

`#`. 1열을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록
하라.

    tensor([[ 0.6614],
            [-0.4519],
            [-1.0276]])

`#`. 2-3열을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록
하라.

    tensor([[ 0.2669,  0.0617],
            [-0.1661, -1.5228],
            [-0.5631, -0.8923]])

`#`. 2-3행을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록
하라.

    tensor([[-0.4519, -0.1661, -1.5228,  0.3817],
            [-1.0276, -0.5631, -0.8923, -0.0583]])

## `$`. 회귀(2d)

아래의 데이터를 고려하자.

In [22]:
df = pd.read_csv("https://raw.githubusercontent.com/guebin/DL2025/main/posts/regression_2d.csv")
x1 = torch.tensor(df.x1).float().reshape(-1,1)
x2 = torch.tensor(df.x2).float().reshape(-1,1)
y = torch.tensor(df.y).float().reshape(-1,1)

$x_1, x_2$ 에서 $y$로 향하는 규칙을 찾기 위해 아래와 같은 모형을
고려하였다. ($\beta_0,\beta_1,\beta_2$ 대신에 $w_0, w_1, w_2$ 라고
생각해도 무방)

$$y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \epsilon_i \quad i = 1, 2, \ldots, n$$

`1`. 아래의 제약사항에 맞추어서 $\beta_0,\beta_1,\beta_2$의 값을
추정하라.

**제약사항**

1.  `yhat = X@Bhat` 을 만족하는 적당한 `X`, `Bhat`을 선언하여 문제를 풀
    것. (즉 `torch.nn.Linear()` 를 사용하지 말 것)
2.  손실함수는 MSE로 설정하되 `torch.nn.MSELoss()`를 사용하지 말고 직접
    손실을 구할 것
3.  (확률적)경사하강법을 이용하여 update 하되 직접 수식을 입력할 것. 즉
    `torch.optim.SGD()`를 사용하지 말 것.

**hint**: 참값은 $\beta_0=2.5, \beta_1=4 , \beta_2= -2$ 임

`2`. `1`에서 구한 `X`에 대하여 아래의 수식을 이용하여 직접 추정값을
구하여라.

$$\hat{\boldsymbol \beta}^{LSE} = \begin{bmatrix} \hat{\beta}_0^{LSE} \\  \hat{\beta}_1^{LSE} \\  \hat{\beta}_2^{LSE}\end{bmatrix} = ({\bf X}^\top {\bf X})^{-1}({\bf X})^\top {\bf y}$$

1에서 추정한 값과 비교하라. 비슷한가?

`3`. 이 문제에서 모수의 참값은 $\beta_0=2.5, \beta_1=4 , \beta_2= -2$
이다. `epoch`을 증가할수록 `1`에서 추정된 값은 참값에 근접해갈까?
(`epoch`을 무한대로 하면 결국 참값에 수렴할까?)

`4`. 아래의 제약사항에 맞추어서 $\beta_0,\beta_1,\beta_2$의 값을 다시
추정하라.

**제약사항**

1.  `yhat = net(X)` 을 만족하는 적당한 `X`, `net`을 선언하여 문제를 풀
    것. 단 `torch.nn.Linear(??,??,bias=False)` 를 사용할 것.
2.  `torch.nn.MSELoss()`를 이용하여 손실을 구할 것
3.  `torch.optim.SGD()`를 이용하여 update할 것

`5`. 아래의 제약사항에 맞추어서 $\beta_0,\beta_1,\beta_2$의 값을 다시
추정하라.

**제약사항**

1.  `yhat = net(X)` 을 만족하는 적당한 `X`, `net`을 선언하여 문제를 풀
    것. 단 `torch.nn.Linear(??,??,bias=True)` 를 사용할 것.
2.  `torch.nn.MSELoss()`를 이용하여 손실을 구할 것
3.  `torch.optim.SGD()`를 이용하여 update할 것

`#`.