# A1: Exercise

최규빈  
2025-01-01

<a href="https://colab.research.google.com/github/guebin/DL2025/blob/main/posts/exercise.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" style="text-align: left"></a>

> 문제풀이에 필요한 모듈은 스스로 `import` 할 것

## `$` 벡터와 행렬

`#`. 아래와 같이 length 5 인 vector를 `torch.tensor`로 선언하는 코드를
작성하라.

$${\bf x} = [1,2,3,4,5]$$

`(풀이)`

In [2]:
x = torch.tensor([1,2,3,4,5])
x

`#`. 아래와 같은 2x2 matrix 를 `torch.tensor`로 선언하는 코드를
작성하라.

$${\bf A} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$$

`#`. 아래와 같은 matrix 를 `torch.tensor`로 선언하는 코드를 작성하라.

$${\bf W} = \begin{bmatrix} 2.5  \\  4 \end{bmatrix}$$

`#`. 아래와 같은 matrix 를 `torch.tensor`로 선언하는 코드를 작성하라.

$${\bf x} = \begin{bmatrix} 2.5  & 4 \end{bmatrix}$$

`#`. 행렬곱 `@`을 이용하여 아래를 계산하라.

$${\bf x} = \begin{bmatrix} 2.5  & 4 \end{bmatrix}$$

------------------------------------------------------------------------

`##` – a,b가 아래와 같이 주어졌다고 하자.

In [9]:
a = torch.tensor([1]*10)
b = torch.tensor([2]*10)

아래를 잘 읽고 물음에 답하라.

`#` 주어진 a,b와 `torch.concat`를 이용하여 아래와 같은 배열을 만들어라.

    tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
torch.concat([a.reshape(-1,1), b.reshape(-1,1)])

`#` 주어진 a,b 와 `torch.concat`,`.reshape`를 이용하여 아래와 같은
배열을 만들어라.

    tensor([[1],
            [1],
            [1],
            [1],
            [1],
            [1],
            [1],
            [1],
            [1],
            [1],
            [2],
            [2],
            [2],
            [2],
            [2],
            [2],
            [2],
            [2],
            [2],
            [2]])

`#` 주어진 a,b 와 `torch.concat`,`.reshape`를 이용하여 아래와 같은
배열을 만들어라.

    tensor([[1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2]])

`#` 주어진 a,b와 `torch.stack` 을 이용하여 아래와 같은 배열을 만들어라.

    tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]

`#` 주어진 a,b와 `torch.stack`을 이용하여 아래와 같은 배열을 만들어라.

    tensor([[1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2],
            [1, 2]])

`##.`

------------------------------------------------------------------------

`#`. 아래와 같은 텐서를 생성하라.

``` python
a = torch.tensor([1,2,3,4,5]).reshape(-1,1)
b = torch.tensor([3,2,1,1,2]).reshape(-1,1)
```

`@` 연산자를 이용하여 $\sum_{i=1}^{5}a_ib_i$를 계산하라.

`#` 아래와 같은 텐서를 생성하라.

``` python
x = torch.randn(100).reshape(-1,1)
```

`@`연산자를 이용하여 $\sum_{i=1}^{100}x_i^2$을 계산하라.

`##` – 아래와 같은 배열을 선언하라.

In [23]:
torch.manual_seed(1)
x = torch.randn(12).reshape(3,4)
x

`#`. 1열을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록
하라.

    tensor([[ 0.6614],
            [-0.4519],
            [-1.0276]])

`#`. 2-3열을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록
하라.

    tensor([[ 0.2669,  0.0617],
            [-0.1661, -1.5228],
            [-0.5631, -0.8923]])

`#`. 2-3열을 추출하는 코드를 작성하라. 즉 결과가 아래와 같이 나오도록
하라.

    tensor([[-0.4519, -0.1661, -1.5228,  0.3817],
            [-1.0276, -0.5631, -0.8923, -0.0583]])

`##`